server:
  port: 8888


spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Desktop/dev_stduy/native-file-repo
        git:
          uri: C:\Users\E132297\Desktop\dev_stduy\git-local-repo
#          username: [? ???]
#          password: [? ??]
#          uri: git ?? ?? ??? ?